spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: catalog
    password: catalog
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - public
      - catalog
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info
